# Base
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="${PNPM_HOME}/bin:${PATH}"
RUN corepack enable

# Copy Files
WORKDIR /frontend
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY public ./public
COPY src ./src
COPY tsconfig.json ./
COPY .env.production ./.env

# Install Dependencies
FROM base AS dependencies
RUN --mount=type=cache,target=/pnpm \
  pnpm install --frozen-lockfile --production

# Build
FROM base AS build
RUN --mount=type=cache,target=/pnpm \
  pnpm install --frozen-lockfile
RUN pnpm build:server
EXPOSE 5173
CMD ["node", "server"]
# RUN pnpm start

# Release
# FROM base AS release
# COPY --from=dependencies /frontend/node_modules ./node_modules
# COPY --from=build /frontend/build /usr/share/nginx/html
# COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf
# RUN apk update
# RUN apk upgrade

# CMD ["nginx", "-g", "daemon off;"]
