---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: k8sdeploy
  labels:
    name: dashboard
    app: dashboard
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: dashboard
  template:
    metadata:
      labels:
        name: dashboard
        app: dashboard
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend
          image: containers.chewed-k8s.net/k8sdeploy/dashboard:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: VITE_APP_KEYCLOAK_URL
              value: https://keys.chewedfeed.com/realms/k8sdeploy
            - name: VITE_APP_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets-dev
                  key: keycloak-client-id
            - name: VITE_APP_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets-dev
                  key: keycloak-client-secret
            - name: REACT_APP_BACKEND_URL
              value: https://api.k8sdeploy.dev
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: k8sdeploy
  labels:
    name: dashboard
    app: dashboard
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: k8sdeploy
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: dashboard
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboard.k8sdeploy.dev
      secretName: dashboard-dev-tls
  rules:
    - host: dashboard.k8sdeploy.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80
